- name: 'drive'
  service: 'drive'
  column: 0
- name: 'valve'
  service: 'valve'
  column: 0
- name: 'door'
  service: 'door'
  column: 0
- name: 'debri'
  service: 'debri'
  column: 0
- name: 'hose_grasp'
  service: 'hose_grasp'
  column: 0
- name: 'hose_connect'
  service: 'hose_connect'
  column: 0
- name: 'drill-grasp'
  service: 'drill_grasp'
  column: 0
- name: 'drill-button'
  service: 'drill_button'
  column: 0
- name: 'drill-wall'
  service: 'drill_wall'
  column: 0
- name: 'drill-put'
  service: 'drill_put'
  column: 0
- name: 'Go pos'
  service: 'go_pos'
  image: "package://drc_task_common/icons/gopos.png"
  column: 1
- name: 'Look at'
  service: 'look_at'
  image: "package://drc_task_common/icons/lookat.png"
  column: 1
- name: 'Look around'
  service: 'look_around'
  column: 1
- name: 'exec'
  service: 'exec'
  image: "package://drc_task_common/icons/exec.png"
  column: 2
- name: 'cancel'
  service: 'cancel'
  image: "package://drc_task_common/icons/cancel.png"
  column: 2
- name: 'show_motion'
  service: 'reflesh'
  image: "package://drc_task_common/icons/refresh.png"
  column: 2
- name: 'cancel-motion-now'
  service: 'cancel_motion_now'
  #image: "package://drc_task_common/icons/cancel.png" # todo
  column: 2
- name: 'skip-recog'
  service: 'skip_recog'
  column: 2
- name: 'enable-head-overwrite'
  service: 'enable_head_overwrite'
  image: "package://drc_task_common/icons/enable-head-overwrite.png"
  column: 2
- name: 'disable-head-overwrite'
  service: 'disable_head_overwrite'
  image: "package://drc_task_common/icons/disable-head-overwrite.png"
  column: 2
